/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Crud: typeof import('./src/components/crud.vue')['default']
    EmployeeForm: typeof import('./src/components/EmployeeForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    HomeComponent: typeof import('./src/components/HomeComponent.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpComponent: typeof import('./src/components/SignUpComponent.vue')['default']
    SignUpForm: typeof import('./src/components/SignUpForm.vue')['default']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
  }
}
