/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HomeComponent: typeof import('./src/components/HomeComponent.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpComponent: typeof import('./src/components/SignUpComponent.vue')['default']
    SignUpForm: typeof import('./src/components/SignUpForm.vue')['default']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
  }
}
